version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      #      - "8080:80"
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/letsencrypt/www/:/var/www/certbot/:ro
      - ./docker/letsencrypt/conf/:/etc/letsencrypt/:ro
      #      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/letsencrypt/www/:/var/www/certbot:rw
      - ./docker/letsencrypt/conf/:/etc/letsencrypt/:rw

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:delegated
      #      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - "9000:9000"
    #      - "3000:3000" # BROWSERSYNC_HOST_PORT
    #      - "3001:3001" # BROWSERSYNC_HOST_PORT
    #    depends_on:
    #      - nginx
    #      - mysql
    networks:
      - laravel
  #    environment:
  #      PHP_IDE_CONFIG: "serverName=Docker_xdebug"
  #      PHP_XDEBUG_ENABLED: 1
  #      XDEBUG_CONFIG: "remote_host=10.254.254.254"

  composer:
    build:
      context: .
      dockerfile: ./docker/php/composer/Dockerfile
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node:16
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  artisan:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
  meilisearchdata:
    driver: local
