FROM node:16 AS node

FROM bitnami/minideb:latest

COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir "language-server"
RUN wget https://github.com/sumneko/lua-language-server/releases/download/2.6.8/lua-language-server-2.6.8-linux-arm64.tar.gz
RUN mkdir -p /language-server/lua-language-server && tar -xf lua-language-server-2.6.8-linux-arm64.tar.gz -C /language-server/lua-language-server
RUN rm lua-language-server-2.6.8-linux-arm64.tar.gz

#ADD ./docker/language-server/node-server/dist/ /language-server/node-server/dist/
ADD ./docker/language-server/node-server/main.js /language-server/node-server/main.js
ADD ./docker/language-server/node-server/package.json /language-server/node-server/package.json
ADD ./docker/language-server/node-server/package-lock.json /language-server/node-server/package-lock.json
RUN cd /language-server/node-server && npm install && npm run build
RUN rm -r /language-server/node-server/node_modules && rm /language-server/node-server/main.js

COPY ./docker/language-server/run.sh /language-server
RUN chmod +x /language-server/lua-language-server/bin/lua-language-server
RUN chmod +x /language-server/run.sh
WORKDIR /language-server/node-server
ENTRYPOINT ["/language-server/run.sh"]
