name: Continuous Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: Deploy to DigitalOcean
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/git_action/diplomka/ && git pull https://${{ secrets.GIT_KEY }}@github.com/meda10/diplomka.git

      - name: Docker Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/git_action/diplomka/
            docker-compose run --rm artisan config:cache
            docker-compose run --rm artisan route:cache
            docker-compose run --rm npm run production
            docker-compose up -d nginx

  rebuild-and-deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: Deploy to DigitalOcean
    if: "contains(github.event.head_commit.message, '[rebuild]')"
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.PORT }}
          script: cd /home/git_action/diplomka/ && git pull https://${{ secrets.GIT_KEY }}@github.com/meda10/diplomka.git

      - name: Docker Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/git_action/diplomka/
            docker-compose run --rm composer update --no-dev
            docker-compose run --rm composer install --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader
            docker-compose run --rm artisan key:generate
            docker-compose run --rm artisan migrate:fresh --seed
            docker-compose run --rm artisan config:cache
            docker-compose run --rm artisan route:cache
            docker-compose run --rm npm ci
            docker-compose run --rm npm run production
            docker-compose up -d nginx

