name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - run: echo $USER
      - name: Checkout main branch
        uses: actions/checkout@v2

      - uses: docker-practice/actions-setup-docker@master
    
      - name: docker pre-install
        run: docker --version
        
#       - name: Docker Compose
#       - uses: isbang/compose-action@v1.0.0
      
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '14.x'

#       - name: Install dependencies
#         run: npm ci

#       - name: Test application
#         run: npm test

#       - name: Build application
#         run: npm run build
